EMAIL_TEMPLATE_TYPE: professional
HUNTER_API_KEY: your_hunter_api_key_here
HUNTER_REQUESTS_PER_MINUTE: '10'
MAX_PRODUCTS_PER_RUN: '50'
MAX_PROSPECTS_PER_COMPANY: '10'
NOTION_TOKEN: your_notion_token_here
OPENAI_API_KEY: your_openai_api_key_here
PERSONALIZATION_LEVEL: medium
SCRAPING_DELAY: '0.3'

# Sender Profile Configuration
SENDER_PROFILE_PATH: profiles/sender_profile.md
SENDER_PROFILE_FORMAT: markdown
ENABLE_SENDER_PROFILE: 'true'
ENABLE_INTERACTIVE_PROFILE_SETUP: 'true'
REQUIRE_SENDER_PROFILE: 'false'
SENDER_PROFILE_COMPLETENESS_THRESHOLD: '0.7'
